### ISSUE TITLE
Support VS 2019

### ISSUE THREAD

**Issue by shoaibshakeel381** [nbelyh/ClosePrompt#1]
Can you please add support for VS 2019.

**Comment by nbelyh** [comment]
Did not install 2019 yet. Hopefully should be just a manifest change.

**Comment by phoffman81** [comment]
Just the manifest change does it. I've forked it and made the change, haven't done any comprehensive testing but it seems to function as well as it did before.

**Comment by shoaibshakeel381** [comment]
@phoffman81 can you maybe create a PR.

**Comment by phoffman81** [comment]
Huh... Totally thought I already did... I'll take care of it

**Comment by phoffman81** [comment]
The pull request was already created and merged

**Comment by nbelyh** [comment]
It is done already, the relevant PR is merged. Just need to update the VSIX on markeplace, then we can close the issue.

**Comment by nbelyh** [comment]
Updated release on github and marketplace to 1.2 (support VS 2019)
