### ISSUE TITLE
Support VS 2022

### ISSUE THREAD

**Issue by shoaibshakeel381** [nbelyh/ClosePrompt#5]
Can you please add support for VS 2022

**Comment by shoaibshakeel381** [comment]
I had some free time so added support https://github.com/nbelyh/ClosePrompt/pull/6

**Comment by nbelyh** [comment]
I have decided not to make a separate extension for 2022, just updated the configuration for the current one (minimal changes) so that it works with previous and current releases. Sorry it took that long.
https://github.com/nbelyh/ClosePrompt/commit/6ca3b5b84b33fc187934da5a886abfb809dd3361

**Comment by nbelyh** [comment]
Updated on the marketplace as well, now there should be the latest one.
